# Generated by Django 4.1.1 on 2022-09-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop100', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('catid', models.AutoField(db_column='catId', primary_key=True, serialize=False)),
                ('catname', models.CharField(db_column='catName', max_length=30, unique=True)),
            ],
        ),
    ]
