# Generated by Django 4.1.1 on 2022-09-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop100', '0002_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('modelid', models.AutoField(primary_key=True, serialize=False, verbose_name='modelId')),
                ('modelname', models.CharField(max_length=30, unique=True, verbose_name='modelName')),
            ],
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
        migrations.AlterField(
            model_name='range',
            name='rangeid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='rangeId'),
        ),
        migrations.AlterField(
            model_name='range',
            name='rangename',
            field=models.CharField(max_length=30, unique=True, verbose_name='rangeName'),
        ),
    ]
