# Generated by Django 4.1.1 on 2022-09-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop100', '0003_models_delete_cat_delete_dog_alter_range_rangeid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='idrange',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='shop100.range', verbose_name='idRange'),
        ),
    ]
