# Generated by Django 4.1.1 on 2022-09-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop100', '0004_models_idrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='image',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='models',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='models',
            name='producer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
