# Generated by Django 4.1.1 on 2022-09-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop100', '0005_models_image_models_price_models_producer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False, verbose_name='itemId')),
            ],
        ),
    ]
