# Generated by Django 4.1.1 on 2022-09-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop100', '0009_alter_stock_idmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='size',
            field=models.CharField(default='M', max_length=4),
        ),
    ]
